apiVersion: "kafka.jikkou.io/v1beta2"
kind: "KafkaTopicList"
items:
  - metadata:
      name: "my-first-topic"
    spec:
      partitions: 5
      replicationFactor: 1
      configs:
        cleanup.policy: "compact"

  - metadata:
      name: "my-second-topic"
      annotations:
        jikkou.io/delete: true
    spec:
      partitions: 4
      replicationFactor: 1
      configs:
        cleanup.policy: "delete"

  - metadata:
      name: "frosttide-command-service-output"
    spec:
      partitions: 1
      replicationFactor: 1
      configs:
        cleanup.policy: "compact"

  - metadata:
      name: "finnhub-websocket-trades-event-processor-input"
    spec:
      partitions: 1
      replicationFactor: 1
      configs:
        cleanup.policy: "compact"

  - metadata:
      name: "finnhub-websocket-trades-event-processor-output"
    spec:
      partitions: 1
      replicationFactor: 1
      configs:
        cleanup.policy: "compact"

  - metadata:
      name: "frosttide-broker-account-input"
    spec:
      partitions: 1
      replicationFactor: 1
      configs:
        cleanup.policy: "compact"

  - metadata:
      name: "frosttide-broker-account-output"
    spec:
      partitions: 1
      replicationFactor: 1
      configs:
        cleanup.policy: "compact"
